name: publish
on: [workflow_dispatch]

on:
  push:
    branches:
      - main   # change if you want another branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          npm install -g parcel
          npm install   # if you have a package.json

      # 4. Build project with Parcel
      - name: Build with Parcel
        run: |
          parcel build index.html --dist-dir dist

      # 5. Upload artifact (optional, useful to test build output)
      - name: Upload build output
        uses: actions/upload-artifact@v3
        with:
          path: dist
      
      # 6. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
